[environments]
  [environments.development]
    name = "tzone"
    namespace = "default"
    wait = false
    watch = false
    watch-delay = 2
    auto-connect = false
    override-ports = ["3000:3000"]
